<div>
    <h2><?php echo $this->title?>,</h2>
    <p><?php echo $this->message?></p>
    <p>Another variable: <?php echo $this->another_variable?></p>
    <a href="/second">
        <button><?php echo $this->first_button_caption?></button>
    </a>
    <a class="database" href="/database">
        <button class="default">Database</button>
    </a>
    <a class="form" href="/form">
        <button class="default">Form</button>
    </a>
</div>